name: NuGet - Npgsql

on:
  push:
    paths:
      - 'src/Thinktecture.EntityFrameworkCore.Npgsql/Thinktecture.EntityFrameworkCore.Npgsql.csproj'

jobs:
  publish-npgsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack Npgsql
        run: |
          dotnet pack src/Thinktecture.EntityFrameworkCore.Npgsql/Thinktecture.EntityFrameworkCore.Npgsql.csproj -c Release -o ./artifacts

      - name: Publish Npgsql package(s)
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: "https://nuget.pkg.github.com/Stellar-Blue/index.json"
        run: |
          dotnet nuget push "./artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source "$NUGET_SOURCE" --skip-duplicate
